// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewfvuphgvxwunejpkuls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3ZnZ1cGhndnh3dW5lanBrdWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTY1MjEsImV4cCI6MjA2NTE3MjUyMX0.RhQhhG9eJSjciKkNSCHNnMZCk_zDgSOiQCSfNxPgQtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);